package io.github.alexarchambault.nativeterm;

import java.util.Objects;

/**
 * Terminal size
 */
public final class TerminalSize {
    private final int width;
    private final int height;

    TerminalSize(int width, int height) {
        this.width = width;
        this.height = height;
    }

    /**
     * Create a {@code TerminalSize} instance
     * @param width terminal width
     * @param height terminal height
     * @return the freshly built instance
     */
    public static TerminalSize of(int width, int height) {
        return new TerminalSize(width, height);
    }


    // methods below are generated by IntelliJ

    /**
     * Gets the terminal height
     * @return the terminal height
     */
    public int getHeight() {
        return height;
    }

    /**
     * Gets the terminal width
     * @return the terminal width
     */
    public int getWidth() {
        return width;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TerminalSize size = (TerminalSize) o;
        return width == size.width &&
                height == size.height;
    }

    @Override
    public int hashCode() {
        return Objects.hash(width, height);
    }

    @Override
    public String toString() {
        return "TerminalSize{" +
                "width=" + width +
                ", height=" + height +
                '}';
    }
}
